version: '3.9'

services:
  # сервис для разработки веб-приложения
  web_dev:
    container_name: web_dev
    build:
      dockerfile: docker/Dockerfile
      context: .
    ports:
      - "8002:8000"
    command: scripts/web_dev/startup.sh -m -l
    restart: on-failure
    env_file:
      - ./conf/.env
    volumes:
      - .:/code
    depends_on:
      web_db_dev:
        condition: service_healthy
    networks:
      - sirius_network

  rabbitmq:
    image: rabbitmq:3.10.7-management
    ports:
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=rmuser
      - RABBITMQ_DEFAULT_PASS=rmpassword
    networks:
      - sirius_network

  # сервис с образом PostgreSQL для базы данных
  web_db_dev:
    container_name: web_db_dev
    image: library/postgres:13.2
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=main_db
      - POSTGRES_HOST=web_db_dev
    restart: on-failure
    ports:
      - "5433:5432"
    command: [ "postgres", "-c", "log_statement=all", "-c", "log_destination=stderr" ]
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "postgres", "-d", "main_db" ]
      interval: 5s
      retries: 5
    volumes:
      - ./scripts/postgres:/docker-entrypoint-initdb.d
    networks:
      - sirius_network

  redis_dev:
    container_name: redis_dev
    image: redis:6.2.4
    ports:
      - "6378:6379"
    networks:
      - sirius_network

  minio:
    image: minio/minio:RELEASE.2023-11-01T01-57-10Z-cpuv1
    command: server --console-address ":9001" /data/
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minio123
    ports:
      - "9000:9000"
      - "9001:9001"
    networks:
      - sirius_network

  prometheus_dev:
    image: prom/prometheus
    container_name: prometheus_dev
    command:
      - "--config.file=/etc/prometheus/prometheus_config.yml"
    ports:
      - "9090:9090"
    restart: unless-stopped
    depends_on:
      - web_dev
    volumes:
      - ./prometheus:/etc/prometheus
      - prom_data:/prometheus
    networks:
      - sirius_network

  grafana_dev:
    image: grafana/grafana
    container_name: grafana_dev
    ports:
      - "3000:3000"
    restart: unless-stopped
    env_file: grafana/.env
    volumes:
      - ./grafana:/etc/grafana/provisioning/datasources
    depends_on:
      - web_dev
    networks:
      - sirius_network

volumes:
  prom_data:

networks:
  sirius_network:
    external: True
